## Домашнее задание по 2й лекции урока 1

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    


__РЕШЕНИЕ__

a)  произведение неопределено,  т.к. число столбцов A = 2 не равно числу строк B = 4 и наоборот

б)  произведение AB определено с размерностью 2х3, BA неопределено, т.к. число строк А не равно числу столбцов B.

в)  произведение определено для обоих произведений, с размерностями  AB 8x8 и BA 2x3 

г)  произведение определено для обоих произведений, размерность AB - 4х4, размерност BA - 4х4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__РЕШЕНИЕ__

In [1]:
import numpy as np

A + B = $\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ + 
$\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ =
$\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$


A * B = $\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ + 
$\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ =
$\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

Проверка:

In [8]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
a+b, np.dot(a, b)

(array([[ 5, -3],
        [ 3,  5]]),
 array([[  4, -11],
        [ 12,  -3]]))

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

__РЕШЕНИЕ__

In [9]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, -5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

lc = 3*a - 2*b + 4*c
lc

array([[ 11,  15],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__РЕШЕНИЕ__

$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\
2 & 3
\end{pmatrix}$, 

$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$, 

$AA^{T}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}.$

$A^{T}A=\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}.$

Проверка:

In [15]:
a = np.array([[4, 1], [5, -2],[2, 3]])
at = a.T
aa𝑇 = np.dot(a, at)
a𝑇a = np.dot(at, a)
a,at,aa𝑇,a𝑇a 

(array([[ 4,  1],
        [ 5, -2],
        [ 2,  3]]),
 array([[ 4,  5,  2],
        [ 1, -2,  3]]),
 array([[17, 18, 11],
        [18, 29,  4],
        [11,  4, 13]]),
 array([[45,  0],
        [ 0, 14]]))

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

__РЕШЕНИЕ__

In [90]:
a = [[ 8 , 5 , 3],[ 4, 6, 1],[ 0,11,  9],[ 2, 7,10]]
b = [[ 8,  4,  0,  2],[ 5,  6, 11,  7],[ 3,  1,  9, 10]]

n = len(a)
m = len(a[0])
l = len(b)
k = len(b[0])
ab = [[[0] for i in range(k)] for j in range(n)] 

[[8, 5, 3], [4, 6, 1], [0, 11, 9], [2, 7, 10]]

In [120]:
if n == k and m == l:
    for col in range(n):
        for i in range(n):
            s = 0
            for j in range(m):
                s += a[i][j]* b[j][col]
            ab[col][i] = s
    print('произведение определено и равно:\n', ab  )
else:
    print('произведение не определено')

произведение определено и равно:
 [[98, 65, 82, 81], [65, 53, 75, 60], [82, 75, 202, 167], [81, 60, 167, 153]]


Проверка:

In [121]:
np.dot(a,b)

array([[ 98,  65,  82,  81],
       [ 65,  53,  75,  60],
       [ 82,  75, 202, 167],
       [ 81,  60, 167, 153]])

## Домашнее задание по 2й лекции урока 2

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

__РЕШЕНИЕ__

a): sinx * sinx + cosx * cosx = sinx ^ 2 + cosx ^ 2 = 1

In [124]:
print(f'б): {np.linalg.det(np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])):.0f}')
print(f'в): {np.linalg.det(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])):.0f}')

б): 180
в): 0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__РЕШЕНИЕ__

   а) $det(A^{2}) = det(AA) = det(A) * det(A) = 4 * 4 = 16 $;
    
   б) $det(A^{T}) = det(A) = 4 $;
    
   в) $det(2A) =  2 * 4 = 8 $.

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__РЕШЕНИЕ__

In [127]:
d = np.linalg.det(np.array([[2, 7, -3], [4, -14, 6], [-3, 7, 13]]))
if d == 0:
    print(f'Матрица вырожденная т.к. ее определитель равен {d}')
else:
    print(f'Матрица не вырожденная т.к. ее определитель равен {d}')

Матрица не вырожденная т.к. ее определитель равен -895.9999999999991


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__РЕШЕНИЕ__

In [129]:
print(f'a): {np.linalg.matrix_rank(np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]]))}')
print(f'б): {np.linalg.matrix_rank(np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]]))}')

a): 2
б): 3
