## Домашнее задание по лекции 3

In [11]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

## __1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

__РЕШЕНИЕ__

найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(6-\lambda)-2\cdot-6=0,$$

$$\lambda^{2} - 5\lambda + 6 = 0,$$

Найдем дискриминант квадратного уравнения:

$D = b^{2} - 4ac =  5^{2} - 4\cdot1\cdot6 = 25 - 24 = 1$

Так как дискриминант больше нуля то, квадратное уравнение имеет два действительных корня:

$\lambda1 =   \frac{-b - \sqrt{D}}{2a}  =   \frac{5 - 1}{2}  = 2$

$\lambda2 =   \frac{-b + \sqrt{D}}{2a}  =   \frac{5 + 1}{2}  = 3$



Теперь найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученные собственные значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получим

$$\begin{cases}
-1\cdot x_{1}-6\cdot x_{2}= 3x_{1}, \\
2\cdot x_{1}+6\cdot x_{2}= 3x_{2}.
\end{cases}$$ 

Перенеся все в левую часть, получим

$$\begin{cases}
2 x_{1}+3 x_{2} = 0, \\
2 x_{1}+3 x_{2} = 0;
\end{cases}$$ 

$$\begin{cases}
x_{1}=0, \\
x_{2} = 0.
\end{cases}$$

И,
$$\begin{cases}
-1\cdot x_{1}-6\cdot x_{2}= 2x_{1}, \\
2\cdot x_{1}+6\cdot x_{2}= 2x_{2}.
\end{cases}$$ 

Перенеся все в левую часть, получим

$$\begin{cases}
x_{1}+2 x_{2} = 0, \\
x_{1}+2 x_{2} = 0;
\end{cases}$$ 

$$\begin{cases}
x_{1}=0, \\
x_{2} = 0.
\end{cases}$$

## тут я не понял где я начал ошибаться!!!

In [19]:
'''проверка'''
a = np.array([[-1, -6],[2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


## __2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

__РЕШЕНИЕ__

найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & -0\\ 
0 & -1-\lambda
\end{vmatrix} = 0,$$

$$\lambda=1$$

Теперь найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученные собственные значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получим

$$\begin{cases}
-1\cdot x_{1}+0\cdot x_{2}= x_{1}, \\
0\cdot x_{1}+-1\cdot x_{2}= x_{2}.
\end{cases}$$ 

$$\begin{cases}
x_{1} =0, \\
x_{2} = 0.
\end{cases}$$

соответственно, уравнение будет удовлетворять любым векторам

In [18]:
'''проверка'''
a = np.array([[-1, 0],[0, -1]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


### Не понимаю почему не сходятся собственные векторы!!!

## __3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.



найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
1-\lambda & 1\\ 
-1 & 3-\lambda
\end{vmatrix} = 0,$$

$$\lambda^{2} - 4\lambda + 4 = 0,$$
$$D = 0,$$
$$\lambda=2$$

Получим

$$\begin{cases}
1\cdot x_{1}+1\cdot x_{2}= 2 x_{1}, \\
-1\cdot x_{1}+3\cdot x_{2}= 2 x_{2}.
\end{cases}$$ 

$$\begin{cases}
x_{1} = x_{2}, \\
0 = 0.
\end{cases}$$

In [17]:
'''проверка'''
a = np.array([[-1, 0],[0, -1]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


соответственно, уравнение будет удовлетворять любым собственным векторам, в том числе и (1,1)

## __4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

__Решение__

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора. Аналогично методике из предыдущего примера получим:

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$$

$$\Rightarrow
\begin{cases}
\lambda=3\\ 
\lambda=-3\\
\lambda=3
\end{cases}
\Rightarrow
система не имеет смысла.$$

Таким образом, вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора, заданного матрицей $A$, и его собственное значение составляет $\lambda=[ 3. -3.  3.].$

In [16]:
'''проверка'''
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]


вектор $x=(3, -3, -4)$ не является собственным вектором этого линейного оператора.