## Домашнее задание по лекции 4 

### часть 1

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__РЕШЕНИЕ__

Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Путем элементарных преобразований постараемся привести матрицу к ступенчатому виду.

Вычтем из третьей строки первую и из второй первую, умноженную на 2:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Пусть: $$x_{4}= с$$

В итоге после преобразований мы получили матрицу треугльного вида, которая представляет следующую систему:

$$\begin{cases}
x_{1}+x_{2}-x_{3}=2с, \\
~~~~-x_{2}+x_{3}=-2 - 5с, \\
~~~~~~~~~~~~~~~~~x_{3}=(3с-4)/2
\end{cases}$$

Проводя обратный ход метода Гаусса, последовательн подставляя известные значения в уравнения, получим

$$x_{3}=(3c -4)/2,$$

$$x_{2}=13c/2,$$

$$x_{1}=-3c-2.$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

__РЕШЕНИЕ__

In [4]:
import numpy as np

In [105]:
def check_solve(item, x,b):
    A = np.append(x, b.T, axis=1)
    r_x = np.linalg.matrix_rank(x)
    r_a = np.linalg.matrix_rank(A)
    n = x.shape[1]
    solve = 0
    if r_x == r_a and r_x == n:
        solve = np.linalg.solve(x, b[0])
        print(f'{item}) ранг A: {r_x} = рангу A": {r_a}  = n: {n}  где n — число неизвестных, следовательно система определена и имеет решение: {solve}')
    if r_x == r_a and r_x < n:
        print(f'{item}) ранг A: {r_x} = рангу A": {r_a}  < n: {n}  где n — число неизвестных, следовательно система определена и имеет бесконечное количество решений')
    if r_x != r_a:     
        print(f'{item}) ранг A: {r_x} не равна рангу A": {r_a}, следовательно система несовместна и не имеет решений') 
        
    return solve

In [106]:
x = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([[4, -17, 0]])
check_solve('a',x,b)
x = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([[1, 1, 5]])
check_solve('б',x,b)
x = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([[4, -2]])
check_solve('в',x,b)

a) ранг A: 3 = рангу A": 3  = n: 3  где n — число неизвестных, следовательно система определена и имеет решение: [1. 2. 3.]
б) ранг A: 1 не равна рангу A": 2, следовательно система несовместна и не имеет решений
в) ранг A: 2 = рангу A": 2  < n: 3  где n — число неизвестных, следовательно система определена и имеет бесконечное количество решений


0


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [63]:
x = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([[3, 2, 4, 1]])
check_solve('Решение 3',x,b)

Решение 3) ранг A: 4 = рангу A": 4  = n: 4  где n — число неизвестных, следовательно система определена и имеет решение: [2.76666667 0.3        1.33333333 0.5       ]


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

__РЕШЕНИЕ__

$\begin{vmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & 12
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
c - 7a
\end{matrix}
\end{vmatrix}$

Вторая строка в 2 раза меньше чем третья, следовательно для того чтобы система уравнений была несовместна, нужно чтобы 
$b - 4a$ не была меньше в 2 раза чем $c - 7a$: 

$c \neq 2b - a$ 


При любых соотношений $a$, $b$ и $c$, кроме $c = 2b - a$, система будет несовместна.

### часть 2

__1.__ Решить систему уравнений методом Крамера:
​
   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$
​

__РЕШЕНИЕ__

In [78]:
def kramer(item,x,b):
    d = np.linalg.det(x)
    if d != 0 and x.shape[0]==x.shape[1]:
        solve = []
        for i in range(x.shape[1]):
            xi= x.copy()
            xi[:,i] = b
            solve.append(np.round(np.linalg.det(xi)/d))
        print(f'{item}): {solve}')        
    else:
        if d == 0: print('Система вырождена ')
        if x.shape[0]==x.shape[1]: print('количество неизвестных не равно количеству уравнений')

In [80]:
x = np.array([[1, -2], [3, -4]])
b = np.array([[1, 7]])
kramer('a',x,b)
x = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([[10, -2, 1]])
kramer('б',x,b)

a): [5.0, 2.0]
б): [2.0, -1.0, 1.0]


__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:
​
   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    

__РЕШЕНИЕ__

In [90]:
from scipy import linalg
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
P, L, U = linalg.lu(A)
print(f'A)  L: {L}, U: {U}') 
B = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 2, 53, 33]])
P, L, U = linalg.lu(A)
print(f'Б)  L: {L}, U: {U}')

A)  L: [[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]], U: [[ 3.         26.         30.        ]
 [ 0.         -8.33333333 -8.        ]
 [ 0.          0.          0.4       ]]
Б)  L: [[1.         0.         0.        ]
 [0.66666667 1.         0.        ]
 [0.33333333 0.8        1.        ]], U: [[ 3.         26.         30.        ]
 [ 0.         -8.33333333 -8.        ]
 [ 0.          0.          0.4       ]]


__3*.__ Решить систему линейных уравнений методом $LU$-разложения
​
$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$
​

In [112]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])
P, L, U = linalg.lu(A)
lu, piv = linalg.lu_factor(A)
x = linalg.lu_solve((lu, piv), b)
print(f' x_1 = {x[0]}\n x_2 = {x[1]}\n x_3 = {x[2]}')

 x_1 = -1.0
 x_2 = 0.0
 x_3 = 1.0


__4*.__ Решить систему линейных уравнений методом Холецкого
​
$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$
​

In [113]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
L = np.linalg.cholesky(A)
print(f'L=\n{L} \n L.T=\n{L.T}')

L=
[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]] 
 L.T=
[[ 9. -5.  5.]
 [ 0.  5.  2.]
 [ 0.  0.  3.]]


__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.